version: "3.4"
services:
  db:
    container_name: myDB_Kittiphong
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpass
    ports:
      - 8888:5432
    restart: always