version: "3.4"
services:
  db:
    container_name: myDB
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpass
    ports:
      - 8080:5432
    restart: always
